name: Data QC
on:
  [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2
      with:
        path: exascale_data

    - name: checkout RE engine repo
      uses: actions/checkout@v2
      with:
        repository: kbase/relation_engine
        ref: parser_validation
        path: relation_engine

    - name: copy dataset to correct directory
      shell: bash
      env:
        GITHUB_ACTIONS_CI: 1
      run: |
        mkdir relation_engine/to_validate
        cp -r relation_engine/spec/test/djornl/test_data/* relation_engine/to_validate

    - name: run validation!
      shell: bash
      run: |
        cd relation_engine
        make djornl_validate
